# Generated by Django 4.1.1 on 2022-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBuild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='inicio',
            field=models.IntegerField(),
        ),
    ]
