# Generated by Django 4.1.1 on 2022-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBuild', '0002_alter_obra_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='inicio',
            field=models.CharField(max_length=40),
        ),
    ]
